### ISSUE TITLE
The 'Binder' seems not friendly for unit testing

### ISSUE THREAD

**Issue by mikedev-1** [DeclarativeHub/TheBinderArchitecture#2]
There a lot of binding and app logic inside the `binder` part will make it hard for unit testing.Did you ever consider this problem?

**Comment by srdanrasic** [comment]
Yes, although what makes it hard to unit test is not that there is a lot of binding and app logic in there, but the fact that you have to mock the inputs (service). However, that is a common problem when testing a component that has a dependency on some other component. 

As for the side effects on the view controller, those can easily be check by inspecting the instance.

I would suggest the following approach for testing:

1) To test business logic: write unit tests against the services
2) To test app logic: write UI tests against the app
