### ISSUE TITLE
Better solution for the "updates" and "notifies" arrows in the Binder architecture ?

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/TheBinderArchitecture#4]
### Summary
I have been using the Binder architecture for several months now and it's working pretty well. I actually really like it !

However, I have seen a few patterns starting to emerge in my code. Specifically, I have noticed the need for a set of trigger / response signals in the Service layer which seem complicated. And I was hoping to find a "better way" to go about it.

Those specifically match the "updates" and "notifies" arrows depicted in the [Binder Architecture diagram](https://github.com/DeclarativeHub/TheBinderArchitecture/blob/master/Assets/tba@2x.png), between the Service and Binder components.

### Context
At the root of the issue is usually the same requirement : 

- a UI component (like a button) triggers a call to a Service
- that Service, in turn, calls a set of APIs to a REST endpoint
- the response returned is observed by the Binder to either present a new controller or pop the current one, etc.

The initial connection between the UI component and the Service is usually straightforward to achieve in Binder : 

        controller.inviteButton.reactive.tap.bind(to: controller) { ctrl in
            service.setEmail(email: ctrl.emailField.text!)
        }

Here the "Invite" button, when pressed, will call the "setEmail" method of the Service.

    public func setEmail(email: String) {
        emailAddress.next(email)
    }

But in order to observe the result of the API call that will be performed by the Service, I had to use the following "trick" (or pattern).

### Pattern
Simply put, I am defining an API response signal (LoadingSignal) which gets called every time the "trigger" (SafePublishSubject) goes off, with the required parameters  : 

    private let emailAddress = SafePublishSubject<String>()
    public let authToken: LoadingSignal<AuthToken, ApplicationError>
    public let confirmation: LoadingSignal<[String:String], ApplicationError>

Those 3 are linked during initialization as such : 

    public init() {
        .....
        self.authToken = emailAddress.with(latestFrom: anonToken).flatMapLatest { (arg) -> LoadingSignal<AuthToken, ApplicationError> in
            let (email, token) = arg
            return token.value!
                .changeEmail(with: email)
                .response(using: InvitationService.client)
                .toLoadingSignal()
        }.shareReplay()

        self.confirmation = self.authToken.flatMapValue { token in
            token
                .signinWithEmail()
                .response(using: InvitationService.client)
                .toLoadingSignal()
        }.shareReplay()

    }

And then the "confirmation" signal will get consumed by the controller in the Binder (otherwise the API calls are never completed) : 

        service.confirmation.consumeLoadingState(by: controller).bind(to: controller) { ctrl, conf in
            ctrl.navigationController?.popViewController(animated: true)
        }

### Concern
While this "works" it seems very tedious and can get very confusing while reading the code. So I am wondering if there's a different way to implement this in order to minimize the number of hops where responsibility is yet again delegated.
Could we bind the button's tap signal to something in the Service (rather than to the controller, which also seems wrong) ?

Thanks for your help !

**Comment by npvisual** [comment]
I guess I could change the "triggers" by adding a signature to the function I am calling in the Service. And adding a new function signinWithEmail(token:).

The first function would return a `Signal<AuthToken, ApplicationError>`. And the second function would consume this signal and in turn send a `Signal<[String: String], ApplicationError>, that represents the response from the last trigger.

This would now look like : 

```
    public func setEmail(email: String) -> Signal<AuthToken, ApplicationError> {
        return anonToken
            .flatMapLatest { token in
                return token.value!
                    .changeEmail(with: email)
                    .response(using: InvitationService.client)
        }
    }
    
    public func signinWithEmail(token: AuthToken) -> Signal<[String: String], ApplicationError> {
        return token
            .signinWithEmail()
            .response(using: InvitationService.client)
    }

```

and thus the Binder would tie those signals directly and get the controller to consume the result of the last function as such : 

```
        controller.inviteButton.reactive.tap
            .flatMapLatest { service.setEmail(email: controller.emailField.text!) }
            .flatMapLatest { token in service.signinWithEmail(token: token)}
            .toLoadingSignal()
            .consumeLoadingState(by: controller)
            .bind(to: controller) { ctrl, conf in
                ctrl.navigationController?.popViewController(animated: true)
        }
```

Seems like a better approach, considering how complex the previous one was.

Only drawback is if the first (or any intermediary) signal needs to be captured by another stream of processing...

Also it seems that part of the business logic is now captured in the Binder. So maybe I could collapse the 2 flatMapLatest calls and let the Service handle that via an aggregate function like : 

```
    public func setAndSignInViaEmail(email: String) -> Signal<[String: String], ApplicationError>
```

**Comment by srdanrasic** [comment]
I think you have solved it in your answer, especially with the aggregate function. 

You basically want services that expose functions that return signals. You can then flatMap calls to those functions in the binder like you did. That's where Rx Action is used by some, but it's completely unnecessary because you can just flatMap the function. To get loading state, you can use LoadingSignals.

**Comment by npvisual** [comment]
Ok. I have chosen to keep the LoadingSignals out of the Business logic for most scenarios. I am using them "heavily" in the Binder, so the view controller can consume the state, by simply adding `toLoadingSignal()` after I flatMap the service functions (as depicted in the example above).

Thanks !
