### ISSUE TITLE
Lack of example for the architecture 

### ISSUE THREAD

**Issue by MarcSteven** [DeclarativeHub/TheBinderArchitecture#5]
Perhaps the example can describe it greatly ,so Need some examples for it .

**Comment by npvisual** [comment]
@MarcSteven have you checked [AbsurdGitter](https://github.com/DeclarativeHub/AbsurdGitter) ? I have used it as the starting ground for a project and it's been very helpful.

**Comment by MarcSteven** [comment]
@npvisual  So you should import it into  the project ,that's great
